export const PROFILE_COUNTRIES = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "New Zealand",
  "India",
  "Singapore",
  "United Arab Emirates",
  "Germany",
  "France",
  "Spain",
  "Italy",
  "Netherlands",
  "Sweden",
  "Norway",
  "Denmark",
  "Brazil",
  "Mexico",
  "South Africa",
  "Japan",
  "South Korea",
  "China",
];

export const PROFILE_INDUSTRIES = [
  "Technology",
  "Finance",
  "Healthcare",
  "Manufacturing",
  "Retail",
  "Education",
  "Marketing",
  "Logistics",
  "Real Estate",
  "Energy",
  "Hospitality",
  "Automotive",
  "Telecommunications",
  "Media",
  "Nonprofit",
  "Professional Services",
  "Construction",
  "E-commerce",
  "Consulting",
];
